name: FIC-LAB CI Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile hello.c
        run: gcc -o hello hello.c
      - name: Run hello test
        run: ./hello & sleep 2 && echo "Echo Test Success!"
